name = "naturia"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./out"

[[routes]]
pattern = "naturia.ch/*"
zone_name = "naturia.ch"

[[routes]]
pattern = "www.naturia.ch/*"
zone_name = "naturia.ch"
